### ISSUE TITLE
Need to fix functional tests

### ISSUE THREAD

**Issue by mjschock** [adsk-ui/jq-filter#1]
```
undefined: Script error for: cheerio
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: cheerio
  at <http://requirejs.org/docs/errors.html#scripterror>
    at makeError (http://localhost:9000/node_modules/requirejs/require.js:166:17)
    at HTMLScriptElement.context.onScriptError (http://localhost:9000/node_modules/requirejs/require.js:1696:36)
```

&#8230;

```
'fatal error occurred' 
```

**Comment by mjschock** [comment]
Fixed
